version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      # - image: flungo/inkscape
      # - image: johnodon/inkscape
      - image: harmish/inkscape
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: inkscape --help
      # - run: yarn all
workflows:
  version: 2
  build_if_deploy:
    jobs:
      - build
# workflows:
#   version: 2
#   build_if_deploy:
#     jobs:
#       - build:
#           filters:
#             tags:
#               only: /[0-9]+(\.[0-9]+)*.*/
#       - deploy:
#           requires:
#             - build
#           filters:
#             tags:
#               only: /[0-9]+(\.[0-9]+)*.*/
#             branches:
#               ignore: /.*/